import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'/Users/auny/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:400,height:900}});const errors=[],requests=[];
page.on('pageerror',e=>errors.push(e.message));
await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.route('https://fonts.gstatic.com/**',r=>r.abort());
let buildCount=0;
await page.route('https://wat-we-building-bot.aunysillyme.workers.dev/**',async r=>{const data=r.request().postDataJSON(),path=new URL(r.request().url()).pathname;requests.push({path,data});let result;if(path==='/plan')result={plan:'# Paint\n## build order\n1. Validate dimensions\n2. Calculate tins\n## proof walk\nWalk it',model:'fixture'};else result={html:`<!doctype html><html><body><h1>Paint ${++buildCount}</h1><button id="try">Try it</button><output id="o"></output><script>document.getElementById('try').onclick=()=>document.getElementById('o').textContent='works';<\/script></body></html>`,model:'fixture'};await r.fulfill({json:result})});
await page.addInitScript(()=>{window.copied=[];Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>window.copied.push(text)},configurable:true})});
const url=pathToFileURL(process.cwd()+'/index.html').href;
await page.goto(url);
await page.getByRole('button',{name:'Calculator / estimator',exact:true}).click();assert.match(await page.locator('#shapeNote').textContent(),/calculator shape/);
for(let i=0;i<5;i++){assert(await page.locator('#q'+i).isVisible());assert(await page.locator('#a'+i).inputValue());await page.locator('#q'+i+' [data-next]').click()}
assert(await page.locator('#result').isVisible());assert.match(await page.locator('#out').textContent(),/paint estimator/);
await page.locator('#botBtn').click();await page.waitForFunction(()=>lastPlan.includes('Validate dimensions'));
for(const name of ['Lovable','Bolt','Claude Code','Cursor','Copy for any agent']){await page.locator('[data-export="brief"]').getByRole('button',{name,exact:true}).click();assert.match(await page.evaluate(()=>window.copied.at(-1)),/Validate dimensions/)}
await page.locator('#toAgentBtn').click();await page.locator('#buildBtn').click();await page.waitForFunction(()=>versions.length===1);
assert.match(requests.at(-1).data.brief,/Validate dimensions/);
await page.frameLocator('#frame').locator('#try').click();assert.equal(await page.frameLocator('#frame').locator('#o').textContent(),'works');
assert.match(await page.locator('#walkVerdict').textContent(),/Not verified yet/);
await page.locator('#walkSteps li').nth(0).getByRole('button',{name:'Passed',exact:true}).click();await page.locator('#walkSteps li').nth(1).getByRole('button',{name:'Failed',exact:true}).click();
await page.locator('#failure1').fill('The total stays at zero');await page.locator('#walkSteps li').nth(1).getByRole('button',{name:'Send this back to the agent'}).click();assert.match(await page.locator('#repairRequest').inputValue(),/Failed must-do:.*Proof step:.*total stays at zero/);
await page.locator('#repairBtn').click();await page.waitForFunction(()=>versions.length===2);assert.equal(requests.at(-1).path,'/revise');assert.match(requests.at(-1).data.html,/Paint 1/);assert.match(requests.at(-1).data.request,/total stays at zero/);
await page.locator('#versions').getByRole('button',{name:'v1',exact:true}).click();assert.match(await page.frameLocator('#frame').locator('h1').textContent(),/Paint 1/);assert.match(await page.locator('#walkCount').textContent(),/1 of 4/);
assert.equal(await page.locator('#failure1').inputValue(),'The total stays at zero');
for(const li of await page.locator('#walkSteps li').all())await li.getByRole('button',{name:'Passed',exact:true}).click();assert.match(await page.locator('#walkVerdict').textContent(),/You walked it/);
assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('wwb.walk'))['1'].filter(s=>s.status==='passed').length),4);
await page.locator('[data-export="agent"]').getByRole('button',{name:'Share this build'}).click();const shared=await page.evaluate(()=>window.copied.at(-1));assert(shared.startsWith(url+'#s='));const original=await page.evaluate(()=>ans);
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=400),true);
await page.screenshot({path:'tests/mobile-agent.png',fullPage:true});
await page.goto(shared);assert(await page.locator('#sharedBanner').isVisible());assert.deepEqual(await page.evaluate(()=>ans),original);
console.log('PASS F1 F2 F4 F5 F8 F9: file:// 400px archetype -> five questions -> plan -> exports -> build -> proof failure -> revision -> rewind -> all passed -> share round-trip');
await page.locator('#editBtn').click();await page.locator('#a0').fill('A modern calculator');assert.match(await page.locator('#feedback0').textContent(),/modern.*Try:/);await page.locator('#feedback0').getByRole('button',{name:'Dismiss'}).click();assert.equal(await page.locator('#feedback0').textContent(),'');
await page.locator('#q0 [data-next]').click();await page.locator('#a1').fill('login with email\ncalculate total');assert.match(await page.locator('#feedback1').textContent(),/login.*heavy/);await page.locator('#feedback1').getByRole('button',{name:'Park for v2'}).click();assert.equal(await page.locator('#a1').inputValue(),'calculate total');
await page.evaluate(()=>finish());assert.match(await page.locator('#parking').textContent(),/login with email/);assert.match(await page.locator('#out').textContent(),/Parked for v2 \(do not build\)/);assert.match(await page.locator('#reality').textContent(),/Runs free in the browser/);
await page.evaluate(()=>{ans[1]='database\nlogin\nAI\nemail\nupload\ndomain';finish()});assert.match(await page.locator('#reality').textContent(),/Database.*Auth provider.*AI API key.*Email.*File storage.*Domain/s);
await page.evaluate(()=>{ans[1]='login\ntwo\nthree\nfour\nfive\nsix';dismissed.clear();heavySeen.add('login');mirrorShown=false;showMirror({...currentVersion(),answers:ans,parked:[]})});assert.match(await page.locator('#mirror').textContent(),/You left "modern"/);
await page.evaluate(()=>{dismissed.add('0:modern');mirrorShown=false;showMirror({...currentVersion(),answers:ans,parked:[]})});assert.match(await page.locator('#mirror').textContent(),/6 things/);
await page.evaluate(()=>{ans[1]='login';mirrorShown=false;showMirror({...currentVersion(),answers:ans,parked:[]})});assert.match(await page.locator('#mirror').textContent(),/kept login/);
await page.evaluate(()=>{ans[1]='calculate';mirrorShown=false;showMirror({...currentVersion(),answers:ans,parked:[]})});assert.match(await page.locator('#mirror').textContent(),/called it done/);
await page.evaluate(()=>{walks[currentId].forEach(s=>s.status='passed');mirrorShown=false;showMirror({...currentVersion(),answers:ans,parked:[]})});assert.match(await page.locator('#mirror').textContent(),/That is the habit/);
console.log('PASS F3 F6 F7 F10: explicit parking, vague dismissal, negated server needs, cost rules, all mirror priorities');
await page.goto(url+'#s=invalid!');assert(await page.locator('#q0').isVisible());
await page.evaluate(()=>{ans=['x'.repeat(30000),'b','c','d','e'];shareBuild()});assert.match(await page.locator('#toast').textContent(),/30KB/);
await page.goto(url);await page.locator('#sampleBtn').click();assert.match(await page.locator('#out').textContent(),/habit tracker/);
await page.evaluate(()=>{Object.defineProperty(window,'localStorage',{get(){throw new Error('blocked')},configurable:true});save();persistVersions()});
assert.equal(errors.length,0,errors.join('\n'));
console.log('PASS guards: malformed/oversize share, original sample, denied storage; zero page errors; no 400px overflow');
await browser.close();
